name: debrise
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/debrise/assets/images/vector.svg
    - packages/debrise/assets/images/frame1.svg
    - packages/debrise/assets/images/group.svg
    - packages/debrise/assets/images/undrawaccessaccountre8spm1.svg
    - packages/debrise/assets/images/transitionwipe.png
    - packages/debrise/assets/images/photo202206112242291.png
